name = 'E25DX'
license = 'MIT'
licenselink = 'https://github.com/dumindu/E25DX/blob/main/LICENSE'
description = 'Your next documentation theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/dumindu/E25DX'

# If you have a running demo of the theme
demosite = 'https://learning-rust.github.io/docs/overview/'

# Taxonomy terms
tags = ['documentation', 'blog', 'light', 'dark', 'minimal']
features = ['light mode', 'dark mode', 'syntax highlighting', 'responsive', 'seo', 'customizable']

# If the theme has a single author
[author]
name = 'Dumindu Madunuwan'
homepage = 'https://github.com/dumindu'
